### ISSUE TITLE
Input number range incorrect

### ISSUE THREAD

**Issue by ripvega** [tuanha2000vn/Home-Assistant-Dashboard#21]
The input number slider range is always 0 to 100 even with the input_range being set to 0-24, for example, in HA.

**Comment by tuanha2000vn** [comment]
Can you give more detail, some screenshot...?

**Comment by ripvega** [comment]
Hi.

For example, I have an input_number for setting ‘minutes’ that has a range
of 0-59 in Home Assistant but in Home Dash the range is 0-100, which makes
it harder to set.

I have others with ranges of 1-10, which are even harder to accurately set.

The attached screenshots are of the same input_number.

**Comment by ripvega** [comment]
![D983AEB1-B801-4442-8BA9-FAA76F329EB3](https://user-images.githubusercontent.com/42817627/85370083-155ca800-b526-11ea-901b-867e8b8036ec.png)
![ACBBBB31-F444-4487-9A0B-8F598987D524](https://user-images.githubusercontent.com/42817627/85370088-17266b80-b526-11ea-8320-d5d38e4643f4.png)

**Comment by tuanha2000vn** [comment]
Thank, I'll check this part

**Comment by tuanha2000vn** [comment]
Hope it fixed on version 6.6.5 updated

**Comment by ripvega** [comment]
Thank you!

**Comment by ripvega** [comment]
Thank you for the update but that didn't fix it.

In HassKit it works fine.

When the slider is moved in Hasskit it changes the input_number in HA over the range defined. In HassDash, after the update, the range is still 0-100 and it doesn't make any change in HA. The button does, however, show the HA value correctly.

Here's a video that hopefully shows the situation.

[https://www.icloud.com/photos/#0NOjCIn5rYnOQX-NyeSj9A_kQ](url)

**Comment by tuanha2000vn** [comment]
Thank for the video, I'll make a custom input number and debug tomorrow

**Comment by ripvega** [comment]
Not sure what you did, but today’s update fixed it. Thank you.
