### ISSUE TITLE
Is there an easy way to migrate configuration from former HassKit app?

### ISSUE THREAD

**Issue by frederickjh** [tuanha2000vn/Home-Assistant-Dashboard#31]
Hi!
Thanks for your apps. Today my son tried to install the HassKit only to find it is no longer in the Google Play store. I found that this app was the new app.

Is there an easy way to migrate your configuration from HassKit to Home Assistant Dashboard?

I see that there is a back up and restore but when I make a backup in HassKit and try and restore it in Home Assistant Dashboard, it does not restore.

Thanks in advance for any help you can give!
Frederick

**Comment by tuanha2000vn** [comment]
Sorry no, can't import hasskit data into this app
