### ISSUE TITLE
App 7.2.8 crashes on startup armeabi-v7a

### ISSUE THREAD

**Issue by alexsheyko** [tuanha2000vn/Home-Assistant-Dashboard#37]
Today after update not start app

09-28 12:12:21.475 10155 10749 10749 E AndroidRuntime: Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.thhkstudio.hassdash-LOVNIKDasTLNdqgjJi3p0g==/base.apk"],nativeLibraryDirectories=[/data/app/com.thhkstudio.hassdash-LOVNIKDasTLNdqgjJi3p0g==/lib/arm, /data/app/com.thhkstudio.hassdash-LOVNIKDasTLNdqgjJi3p0g==/base.apk!/lib/armeabi-v7a, /system/lib, /product/lib]]] couldn't find "libflutter.so"

**Comment by tuanha2000vn** [comment]
Thank, checking

**Comment by nassermahrous** [comment]
Hi
Will u pls let me help by sending you a tablet

Best regards
Nasser Mahrous

On 28 Sep 2020, at 06:26, tuanha2000vn <notifications@github.com> wrote:

﻿

Thank, checking
